### ISSUE TITLE
[FEATURE] GUI for calculator

### ISSUE THREAD

**Issue by lavendthomas** [AlixDeclerck/calculator-cucumber#2]
In the current implementation, arithmetic expressions need to be build manually, from scratch. A real calculator has a graphical user interface through which you can enter expressions by pressing the buttons of your calculator, and getting the result of evaluating your expression that will be shown on the calculator's display screen.

**Comment by AlixDeclerck** [comment]
https://github.com/AlixDeclerck/calculator-cucumber/releases/tag/v0.4.0
